-- Clientes por empresa y punto de emisión.
-- Idempotente.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_cliente') THEN
        CREATE TYPE tipo_cliente AS ENUM ('PERSONA_NATURAL', 'PERSONA_JURIDICA');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    identificacion VARCHAR(13) NOT NULL,
    tipo_cliente tipo_cliente NOT NULL DEFAULT 'PERSONA_NATURAL',
    nombres VARCHAR(255) NOT NULL,
    razon_social VARCHAR(255),
    fecha_nacimiento DATE,
    provincia VARCHAR(100),
    canton VARCHAR(100),
    parroquia VARCHAR(100),
    direcciones JSONB NOT NULL DEFAULT '[]'::jsonb,
    telefonos JSONB NOT NULL DEFAULT '[]'::jsonb,
    correos JSONB NOT NULL DEFAULT '[]'::jsonb,
    indice_direccion_principal INTEGER,
    indice_telefono_principal INTEGER,
    indice_correo_principal INTEGER,
    direccion_fiscal TEXT,
    telefono_fiscal VARCHAR(20),
    correo_fiscal VARCHAR(255),
    notas TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_clientes_identificacion_punto UNIQUE (empresa_id, punto_emision_id, identificacion)
);

CREATE INDEX IF NOT EXISTS ix_clientes_empresa_id ON clientes (empresa_id);
CREATE INDEX IF NOT EXISTS ix_clientes_punto_emision_id ON clientes (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_clientes_identificacion ON clientes (identificacion);
CREATE INDEX IF NOT EXISTS ix_clientes_nombres ON clientes (nombres);
